<?php
/**
 * MainTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open weather
 *
 * This is my descriptiongggg
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MainTest Class Doc Comment
 *
 * @category    Class */
// * @description Main
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MainTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Main"
     */
    public function testMain()
    {
    }

    /**
     * Test attribute "temp"
     */
    public function testPropertyTemp()
    {
    }

    /**
     * Test attribute "pressure"
     */
    public function testPropertyPressure()
    {
    }

    /**
     * Test attribute "humidity"
     */
    public function testPropertyHumidity()
    {
    }

    /**
     * Test attribute "temp_min"
     */
    public function testPropertyTempMin()
    {
    }

    /**
     * Test attribute "temp_max"
     */
    public function testPropertyTempMax()
    {
    }
}
