<?php
/**
 * Model0Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * defaultTitle
 *
 * defaultDescription with a change
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Model0Test Class Doc Comment
 *
 * @category    Class */
// * @description Model0
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Model0Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Model0"
     */
    public function testModel0()
    {
    }

    /**
     * Test attribute "coord"
     */
    public function testPropertyCoord()
    {
    }

    /**
     * Test attribute "weather"
     */
    public function testPropertyWeather()
    {
    }

    /**
     * Test attribute "base"
     */
    public function testPropertyBase()
    {
    }

    /**
     * Test attribute "main"
     */
    public function testPropertyMain()
    {
    }

    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {
    }

    /**
     * Test attribute "wind"
     */
    public function testPropertyWind()
    {
    }

    /**
     * Test attribute "clouds"
     */
    public function testPropertyClouds()
    {
    }

    /**
     * Test attribute "dt"
     */
    public function testPropertyDt()
    {
    }

    /**
     * Test attribute "sys"
     */
    public function testPropertySys()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "cod"
     */
    public function testPropertyCod()
    {
    }
}
