# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
 # pull_request:
 #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
 # workflow_dispatch:


jobs:
  deploy-doc:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy API documentation
        uses: bump-sh/github-action@0.1
        with:
          id:  8ce2a764-1ae9-4803-b94c-550639f970a8 
          token: eb87e645764568c359bddd278435bfbf
          file: yaml-resolved-bump/swaggerhub-registry-bump.yaml

